# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-15 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190114_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='source',
            field=models.CharField(blank=True, help_text='Maps to pycsw:Source', max_length=512, null=True),
        ),
    ]
