# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190115_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='identifier',
            field=models.CharField(db_index=True, help_text='Maps to pycsw:Identifier', max_length=255, unique=True),
        ),
    ]
