# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-28 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190128_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='inspire_default_language',
            field=models.CharField(blank=True, choices=[('bul', 'bul'), ('cze', 'cze'), ('dan', 'dan'), ('dut', 'dut'), ('eng', 'eng'), ('est', 'est'), ('fin', 'fin'), ('fre', 'fre'), ('ger', 'ger'), ('gre', 'gre'), ('hun', 'hun'), ('gle', 'gle'), ('ita', 'ita'), ('lav', 'lav'), ('lit', 'lit'), ('mlt', 'mlt'), ('pol', 'pol'), ('por', 'por'), ('rum', 'rum'), ('slo', 'slo'), ('slv', 'slv'), ('spa', 'spa'), ('swe', 'swe')], default='ita', help_text='3 letter code of the default language (see http://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_eng.xsd, simpleType euLanguageISO6392B)', max_length=255, null=True, verbose_name='inspire_default_language'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='inspire_languages_supported',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bul', 'bul'), ('cze', 'cze'), ('dan', 'dan'), ('dut', 'dut'), ('eng', 'eng'), ('est', 'est'), ('fin', 'fin'), ('fre', 'fre'), ('ger', 'ger'), ('gre', 'gre'), ('hun', 'hun'), ('gle', 'gle'), ('ita', 'ita'), ('lav', 'lav'), ('lit', 'lit'), ('mlt', 'mlt'), ('pol', 'pol'), ('por', 'por'), ('rum', 'rum'), ('slo', 'slo'), ('slv', 'slv'), ('spa', 'spa'), ('swe', 'swe')], default='ita', help_text='list of comma separated 3 letter codes of supported languages (see http://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_eng.xsd, simpleType euLanguageISO6392B)', max_length=255, null=True, verbose_name='inspire_languages_supported'),
        ),
        migrations.AlterField(
            model_name='record',
            name='language',
            field=models.CharField(blank=True, choices=[('bul', 'bul'), ('cze', 'cze'), ('dan', 'dan'), ('dut', 'dut'), ('eng', 'eng'), ('est', 'est'), ('fin', 'fin'), ('fre', 'fre'), ('ger', 'ger'), ('gre', 'gre'), ('hun', 'hun'), ('gle', 'gle'), ('ita', 'ita'), ('lav', 'lav'), ('lit', 'lit'), ('mlt', 'mlt'), ('pol', 'pol'), ('por', 'por'), ('rum', 'rum'), ('slo', 'slo'), ('slv', 'slv'), ('spa', 'spa'), ('swe', 'swe')], default='eng', help_text='Maps to pycsw:Language', max_length=3, null=True),
        ),
    ]
