# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-29 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20190128_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='xml',
            field=models.TextField(help_text=' Maps to pycsw:XML'),
        ),
    ]
