# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-21 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20190221_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='inspire_contact_phone',
            field=models.CharField(blank=True, help_text='the telephone number of entity responsible for the INSPIRE/RNDT metadata', max_length=255, null=True, verbose_name='inspire_contact_phone'),
        ),
    ]
