# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-11 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20190328_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='topic_category',
            field=models.CharField(blank=True, choices=[('Farming', 'Rearing of animals and/or cultivation of plants.'), ('Biota', 'Flora and/or fauna in natural environment.'), ('Boundaries', 'Legal land descriptions.'), ('Climatology / Meteorology / Atmosphere', 'Processes and phenomena of the atmosphere.'), ('Economy', 'Economic activities, conditions and employment.'), ('Elevation', 'Height above or below sea level.'), ('Environment', 'Environmental resources, protection and conservation.'), ('Geoscientific Information', 'Information pertaining to earth sciences.'), ('Health', 'Health, health services, human ecology, and safety.'), ('Imagery / Base Maps / Earth Cover', 'Base maps.'), ('Intelligence / Military', 'Military bases, structures, activities.'), ('Inland Waters', 'Inland water features, drainage systems and their characteristics.'), ('Location', 'Positional information and services.'), ('Oceans', 'Features and characteristics of salt water bodies (excluding inland waters).'), ('Planning / Cadastre', 'Information used for appropriate actions for future use of the land.'), ('Society', 'Characteristics of society and cultures.'), ('Structure', 'Man-made construction.'), ('Transportation', 'Means and aids for conveying persons and/or goods.'), ('Utilities / Communication', 'Energy, water and waste systems and communications infrastructure and services.')], help_text='Maps to pycsw:TopicCategory', max_length=255, null=True),
        ),
    ]
