# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-11 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20190411_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='rndt_spatial_resolution',
            field=models.IntegerField(default=1000, verbose_name='RNDT spatial resolution denominator'),
        ),
    ]
