# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-11 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20190411_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='accuracy',
            field=models.FloatField(default=1.0, verbose_name='Positional accuracy in meters'),
        ),
        migrations.AlterField(
            model_name='record',
            name='access_constraints',
            field=models.TextField(blank=True, editable=False, help_text='Maps to pycsw:AccessConstraints', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='alternate_title',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:AlternateTitle', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='classification',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:Classification', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='condition_applying_to_access_and_use',
            field=models.TextField(blank=True, editable=False, help_text='Maps to pycsw:ConditionApplyingToAccessAndUse', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='contributor',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:Contributor', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='coupling_type',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:CouplingType', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='creator',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:Creator', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='degree',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:Degree', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='distance_uom',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:DistanceUOM', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='distance_value',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:DistanceValue', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='format',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:Format', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='geographic_description_code',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:GeographicDescriptionCode', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='identifier',
            field=models.CharField(db_index=True, editable=False, help_text='Maps to pycsw:Identifier', max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='keywords_types',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:Keywordstype', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='links',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:Links', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='metadata_source',
            field=models.CharField(db_index=True, default='local', editable=False, help_text='maps to pycsw:MdSource', max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='operates_on',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:OperatesOn', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='operates_on_identifier',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:OperatesOnIdentifier', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='operates_on_name',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:OperatesOnName', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='operation',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:Operation', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='organization_name',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:OrganizationName', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='other_constraints',
            field=models.TextField(blank=True, editable=False, help_text='Maps to pycsw:OtherConstraints', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='publisher',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:Publisher', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='relation',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:Relation', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='resource_language',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:ResourceLanguage', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='responsible_party_role',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:ResponsiblePartyRole', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='schema',
            field=models.CharField(db_index=True, default='http://www.isotc211.org/2005/gmd', editable=False, help_text='Maps to pycsw:Schema', max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='security_constraints',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:SecurityConstraints', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='service_type',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:ServiceType', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='service_type_version',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:ServiceTypeVersion', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='source',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:Source', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='specification_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='Maps to pycsw:SpecificationDate', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='specification_date_type',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:SpecificationDateType', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='specification_title',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:SpecificationTitle', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='temporal_extent_begin',
            field=models.DateTimeField(blank=True, editable=False, help_text='Maps to pycsw:TempExtent_begin', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='temporal_extent_end',
            field=models.DateTimeField(blank=True, editable=False, help_text='Maps to pycsw:TempExtent_end', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.CharField(blank=True, editable=False, help_text='Maps to pycsw:Type', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='typename',
            field=models.CharField(db_index=True, default='gmd:MD_Metadata', editable=False, help_text='Maps to pycsw:Typename', max_length=100),
        ),
    ]
