# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-29 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_record_rndt_use_limitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='rndt_use_limitation',
        ),
        migrations.AddField(
            model_name='record',
            name='inspire_use_limitation',
            field=models.TextField(blank=True, help_text='Restrictions on data usage and access, inherited from catalog if left blank', null=True, verbose_name='INSPIRE data use limitation'),
        ),
    ]
