# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-29 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_record_project_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='inspire_owner_contact_email',
            field=models.CharField(blank=True, help_text='the email address of the owner, inherited from catalog if left blank', max_length=255, null=True, verbose_name='INSPIRE owner contact email'),
        ),
        migrations.AddField(
            model_name='record',
            name='inspire_owner_contact_organization',
            field=models.CharField(blank=True, help_text='INSPIRE the organization name of the owner, inherited from catalog if left blank', max_length=255, null=True, verbose_name='INSPIRE owner contact organization'),
        ),
        migrations.AddField(
            model_name='record',
            name='inspire_owner_contact_phone',
            field=models.CharField(blank=True, help_text='the telephone number of the owner, inherited from catalog if left blank', max_length=255, null=True, verbose_name='INSPIRE owner contact phone'),
        ),
        migrations.AddField(
            model_name='record',
            name='inspire_owner_contact_url',
            field=models.CharField(blank=True, help_text='the URL of the owner, inherited from catalog if left blank', max_length=255, null=True, verbose_name='INSPIRE owner contact url'),
        ),
        migrations.AlterField(
            model_name='record',
            name='rndt_distributor_contact_email',
            field=models.CharField(blank=True, help_text='the email address of the distributor, inherited from catalog if left blank', max_length=255, null=True, verbose_name='RNDT distributor contact email'),
        ),
        migrations.AlterField(
            model_name='record',
            name='rndt_distributor_contact_organization',
            field=models.CharField(blank=True, help_text='RNDT the organization name of the distributor, inherited from catalog if left blank', max_length=255, null=True, verbose_name='RNDT distributor contact organization'),
        ),
        migrations.AlterField(
            model_name='record',
            name='rndt_distributor_contact_phone',
            field=models.CharField(blank=True, help_text='the telephone number of the distributor, inherited from catalog if left blank', max_length=255, null=True, verbose_name='RNDT distributor contact phone'),
        ),
        migrations.AlterField(
            model_name='record',
            name='rndt_distributor_contact_url',
            field=models.CharField(blank=True, help_text='the URL of the distributor, inherited from catalog if left blank', max_length=255, null=True, verbose_name='RNDT distributor contact url'),
        ),
    ]
