# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-25 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_auto_20200214_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='creation_date',
            field=models.DateField(blank=True, help_text='2.1.2.2 Data creation date', null=True, verbose_name='2.1.2.2 Creation date'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(blank=True, help_text='Maps to pycsw:Date', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='modified_date',
            field=models.DateField(blank=True, help_text='2.1.2.2 Data - Maps to pycsw:Modified', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='publication_date',
            field=models.DateField(blank=True, help_text='2.1.2.2 Data publication date', null=True, verbose_name='2.1.2.2 Publication date'),
        ),
        migrations.AlterField(
            model_name='record',
            name='revision_date',
            field=models.DateField(blank=True, help_text='2.1.2.2 Data revision date', null=True, verbose_name='2.1.2.2 Revision date'),
        ),
    ]
