# Generated by Django 2.2.16 on 2021-01-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_auto_20210122_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='is_valid',
            field=models.BooleanField(default=False, help_text='This field is managed by signals, an invalid catalog will be regenerated by a management command called by CRON', verbose_name='Is valid'),
        ),
    ]
