# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-03 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdu', '0005_auto_20181205_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configs',
            name='output_format',
            field=models.CharField(choices=[('odt', 'ODT'), ('pdf', 'PDF'), ('doc', 'DOC'), ('docx', 'DOCX')], max_length=4, null=True, verbose_name='Results output format'),
        ),
    ]
