# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-13 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0003_auto_20181214_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laws',
            options={'permissions': (('view_laws', 'Can view laws list'), ('manage_articles', 'Can work on articles'))},
        ),
    ]
