# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, help_text=b'Maps to pycsw:Identifier', max_length=255)),
                ('typename', models.CharField(db_index=True, default=b'gmd:MD_Metadata', help_text=b'Maps to pycsw:Typename', max_length=100)),
                ('schema', models.CharField(db_index=True, default=b'http://www.isotc211.org/2005/gmd', help_text=b'Maps to pycsw:Schema', max_length=100)),
                ('metadata_source', models.CharField(db_index=True, default=b'local', help_text=b'maps to pycsw:MdSource', max_length=255)),
                ('insert_date', models.DateTimeField(auto_now_add=True, help_text=b'Maps to pycsw:InsertDate')),
                ('xml', models.TextField(default=b'<gmd:MD_Metadata xmlns:gmd="http://www.isotc211.org/2005/gmd"/>', help_text=b' Maps to pycsw:XML')),
                ('any_text', models.TextField(help_text=b'Maps to pycsw:AnyText')),
                ('language', models.CharField(blank=True, default=b'eng', help_text=b'Maps to pycsw:Language', max_length=3, null=True)),
                ('title', models.CharField(help_text=b'Maps to pycsw:Title', max_length=255, null=True)),
                ('abstract', models.TextField(blank=True, help_text=b'Maps to pycsw:Abstract', null=True)),
                ('keywords', models.CharField(blank=True, help_text=b'Maps to pycsw:Keywords', max_length=255, null=True)),
                ('keywords_types', models.CharField(blank=True, help_text=b'Maps to pycsw:Keywordstype', max_length=255, null=True)),
                ('format', models.CharField(blank=True, help_text=b'Maps to pycsw:Format', max_length=50, null=True)),
                ('source', models.CharField(blank=True, help_text=b'Maps to pycsw:Source', max_length=50, null=True)),
                ('date', models.DateTimeField(blank=True, help_text=b'Maps to pycsw:Date, pycsw:Modified, pycsw:RevisionData, pycsw:CreationDate and pycsw:PublicationDate', null=True)),
                ('type', models.CharField(blank=True, help_text=b'Maps to pycsw:Type', max_length=50, null=True)),
                ('bounding_box', models.TextField(blank=True, help_text=b'Maps to pycsw:BoundingBox', null=True)),
                ('crs', models.CharField(blank=True, help_text=b'Maps to pycsw:CRS', max_length=255, null=True)),
                ('alternate_title', models.CharField(blank=True, help_text=b'Maps to pycsw:AlternateTitle', max_length=255, null=True)),
                ('organization_name', models.CharField(blank=True, help_text=b'Maps to pycsw:OrganizationName', max_length=255, null=True)),
                ('security_constraints', models.CharField(blank=True, help_text=b'Maps to pycsw:SecurityConstraints', max_length=255, null=True)),
                ('parent_identifier', models.CharField(blank=True, help_text=b'Maps to pycsw:ParentIdentifier', max_length=255, null=True)),
                ('topic_category', models.CharField(blank=True, help_text=b'Maps to pycsw:TopicCategory', max_length=255, null=True)),
                ('resource_language', models.CharField(blank=True, help_text=b'Maps to pycsw:ResourceLanguage', max_length=30, null=True)),
                ('geographic_description_code', models.CharField(blank=True, help_text=b'Maps to pycsw:GeographicDescriptionCode', max_length=50, null=True)),
                ('denominator', models.CharField(blank=True, help_text=b'Maps to pycsw:Denominator', max_length=255, null=True)),
                ('distance_value', models.CharField(blank=True, help_text=b'Maps to pycsw:DistanceValue', max_length=50, null=True)),
                ('distance_uom', models.CharField(blank=True, help_text=b'Maps to pycsw:DistanceUOM', max_length=200, null=True)),
                ('temporal_extent_begin', models.DateTimeField(blank=True, help_text=b'Maps to pycsw:TempExtent_begin', max_length=255, null=True)),
                ('temporal_extent_end', models.DateTimeField(blank=True, help_text=b'Maps to pycsw:TempExtent_end', max_length=255, null=True)),
                ('service_type', models.CharField(blank=True, help_text=b'Maps to pycsw:ServiceType', max_length=30, null=True)),
                ('service_type_version', models.CharField(blank=True, help_text=b'Maps to pycsw:ServiceTypeVersion', max_length=30, null=True)),
                ('operation', models.CharField(blank=True, help_text=b'Maps to pycsw:Operation', max_length=30, null=True)),
                ('coupling_type', models.CharField(blank=True, help_text=b'Maps to pycsw:CouplingType', max_length=30, null=True)),
                ('operates_on', models.CharField(blank=True, help_text=b'Maps to pycsw:OperatesOn', max_length=255, null=True)),
                ('operates_on_identifier', models.CharField(blank=True, help_text=b'Maps to pycsw:OperatesOnIdentifier', max_length=255, null=True)),
                ('operates_on_name', models.CharField(blank=True, help_text=b'Maps to pycsw:OperatesOnName', max_length=255, null=True)),
                ('degree', models.CharField(blank=True, help_text=b'Maps to pycsw:Degree', max_length=255, null=True)),
                ('access_constraints', models.TextField(blank=True, help_text=b'Maps to pycsw:AccessConstraints', null=True)),
                ('other_constraints', models.TextField(blank=True, help_text=b'Maps to pycsw:OtherConstraints', null=True)),
                ('classification', models.CharField(blank=True, help_text=b'Maps to pycsw:Classification', max_length=255, null=True)),
                ('condition_applying_to_access_and_use', models.TextField(blank=True, help_text=b'Maps to pycsw:ConditionApplyingToAccessAndUse', null=True)),
                ('lineage', models.TextField(blank=True, help_text=b'Maps to pycsw:Lineage', null=True)),
                ('responsible_party_role', models.CharField(blank=True, help_text=b'Maps to pycsw:ResponsiblePartyRole', max_length=255, null=True)),
                ('specification_title', models.CharField(blank=True, help_text=b'Maps to pycsw:SpecificationTitle', max_length=255, null=True)),
                ('specification_date', models.DateTimeField(blank=True, help_text=b'Maps to pycsw:SpecificationDate', null=True)),
                ('specification_date_type', models.CharField(blank=True, help_text=b'Maps to pycsw:SpecificationDateType', max_length=30, null=True)),
                ('creator', models.CharField(blank=True, help_text=b'Maps to pycsw:Creator', max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, help_text=b'Maps to pycsw:Publisher', max_length=255, null=True)),
                ('contributor', models.CharField(blank=True, help_text=b'Maps to pycsw:Contributor', max_length=255, null=True)),
                ('relation', models.CharField(blank=True, help_text=b'Maps to pycsw:Relation', max_length=255, null=True)),
                ('links', models.CharField(blank=True, help_text=b'Maps to pycsw:Links', max_length=255, null=True)),
            ],
        ),
    ]
