# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190112_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='macro_group',
            new_name='macrogroup',
        ),
        migrations.RemoveField(
            model_name='record',
            name='parent_identifier',
        ),
        migrations.AlterField(
            model_name='record',
            name='catalog',
            field=models.ForeignKey(help_text='Maps to pycsw:ParentIdentifier', on_delete=django.db.models.deletion.CASCADE, to='catalog.Catalog'),
        ),
    ]
