# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190116_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='inspire_conformity_service',
            field=models.CharField(blank=True, choices=[('conformant', 'conformant'), ('notConformant', 'notConformant'), ('notEvaluated', 'notEvaluated')], help_text='the level of INSPIRE conformance for spatial data sets and services (conformant, notConformant, notEvaluated)', max_length=20, null=True, verbose_name='inspire_conformity_service'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='inspire_contact_email',
            field=models.CharField(blank=True, help_text='the email address of entity responsible for the INSPIRE metadata', max_length=255, null=True, verbose_name='inspire_contact_email'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='inspire_contact_organization',
            field=models.CharField(blank=True, help_text='the organization name responsible for the INSPIRE metadata', max_length=255, null=True, verbose_name='inspire_contact_organization'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='inspire_date',
            field=models.DateTimeField(blank=True, help_text=' date of INSPIRE metadata offering (in ISO 8601 format)', null=True, verbose_name='inspire_date'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='inspire_default_language',
            field=models.CharField(blank=True, help_text='the default language (see http://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_eng.xsd, simpleType euLanguageISO6392B)', max_length=255, null=True, verbose_name='inspire_default_language'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='inspire_enabled',
            field=models.BooleanField(default=True, help_text='whether to enable the INSPIRE extension', verbose_name='inspire_enabled'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='inspire_gemet_keywords',
            field=models.CharField(blank=True, help_text='a comma-seperated keyword list of GEMET INSPIRE theme keywords about the service (see http://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_eng.xsd, complexType inspireTheme_eng)', max_length=255, null=True, verbose_name='inspire_gemet_keywords'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='inspire_languages_supported',
            field=models.CharField(blank=True, help_text='supported languages (see http://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_eng.xsd, simpleType euLanguageISO6392B)', max_length=255, null=True, verbose_name='inspire_languages_supported'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='inspire_temp_extent',
            field=models.CharField(blank=True, help_text='temporal extent of the service (in ISO 8601 format). Either a single date (i.e. yyyy-mm-dd), or an extent (i.e. yyyy-mm-dd/yyyy-mm-dd)', max_length=255, null=True, verbose_name='inspire_temp_extent'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Maps to pycsw:Date, pycsw:Modified, pycsw:RevisionData, pycsw:CreationDate and pycsw:PublicationDate', null=True),
        ),
    ]
