# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-28 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190128_1007'),
        ('catalog', '0007_auto_20190118_0814'),
    ]

    operations = [
    ]
