# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-21 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20190221_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='inspire_contact_url',
            field=models.CharField(blank=True, help_text='the URL of entity responsible for the INSPIRE/RNDT metadata', max_length=255, null=True, verbose_name='inspire_contact_url'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='inspire_contact_email',
            field=models.CharField(blank=True, help_text='the email address of entity responsible for the INSPIRE/RNDT metadata', max_length=255, null=True, verbose_name='inspire_contact_email'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='inspire_contact_organization',
            field=models.CharField(blank=True, help_text='the organization name responsible for the INSPIRE/RNDT metadata', max_length=255, null=True, verbose_name='inspire_contact_organization'),
        ),
    ]
