# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-11 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20190411_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='any_text',
            field=models.TextField(editable=False, help_text='Maps to pycsw:AnyText'),
        ),
        migrations.AlterField(
            model_name='record',
            name='identifier',
            field=models.CharField(db_index=True, help_text='Maps to pycsw:Identifier', max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='keywords',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Addresses', 'Addresses'), ('Administrative units', 'Administrative units'), ('Agricultural and aquaculture facilities', 'Agricultural and aquaculture facilities'), ('Area management/restriction/regulation zones and reporting units', 'Area management/restriction/regulation zones and reporting units'), ('Atmospheric conditions', 'Atmospheric conditions'), ('Bio-geographical regions', 'Bio-geographical regions'), ('Buildings', 'Buildings'), ('Cadastral parcels', 'Cadastral parcels'), ('Coordinate reference systems', 'Coordinate reference systems'), ('Elevation', 'Elevation'), ('Energy resources', 'Energy resources'), ('Environmental monitoring facilities', 'Environmental monitoring facilities'), ('Geographical grid systems', 'Geographical grid systems'), ('Geographical names', 'Geographical names'), ('Geology', 'Geology'), ('Habitats and biotopes', 'Habitats and biotopes'), ('Human health and safety', 'Human health and safety'), ('Hydrography', 'Hydrography'), ('Land cover', 'Land cover'), ('Land use', 'Land use'), ('Meteorological geographical features', 'Meteorological geographical features'), ('Mineral resources', 'Mineral resources'), ('Natural risk zones', 'Natural risk zones'), ('Oceanographic geographical features', 'Oceanographic geographical features'), ('Orthoimagery', 'Orthoimagery'), ('Population distribution \u2014 demography', 'Population distribution \u2014 demography'), ('Production and industrial facilities', 'Production and industrial facilities'), ('Protected sites', 'Protected sites'), ('Sea regions', 'Sea regions'), ('Soil', 'Soil'), ('Species distribution', 'Species distribution'), ('Statistical units', 'Statistical units'), ('Transport networks', 'Transport networks'), ('Utility and governmental services', 'Utility and governmental services')], help_text='a comma-seperated keyword list of GEMET INSPIRE theme keywords about the service (see http://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_eng.xsd, complexType inspireTheme_eng)', max_length=1024, verbose_name='INSPIRE GEMET keywords'),
        ),
        migrations.AlterField(
            model_name='record',
            name='topic_category',
            field=models.CharField(blank=True, choices=[('farming', 'Farming - Rearing of animals and/or cultivation of plants.'), ('biota', 'Biota - Flora and/or fauna in natural environment.'), ('boundaries', 'Boundaries - Legal land descriptions.'), ('climatologyMeteorologyAtmosphere', 'Climatology / Meteorology / Atmosphere - Processes and phenomena of the atmosphere.'), ('economy', 'Economy - Economic activities, conditions and employment.'), ('elevation', 'Elevation - Height above or below sea level.'), ('environment', 'Environment - Environmental resources, protection and conservation.'), ('geoscientificInformation', 'Geoscientific Information - Information pertaining to earth sciences.'), ('health', 'Health, health services, human ecology, and safety.'), ('imageryBaseMapsEarthCover', 'Imagery / Base Maps / Earth Cover.'), ('intelligenceMilitary', 'Intelligence / Military - Military bases, structures, activities.'), ('inlandWaters', 'Inland water features, drainage systems and their characteristics.'), ('location', 'Location - Positional information and services.'), ('oceans', 'Oceans - Features and characteristics of salt water bodies (excluding inland waters).'), ('planningCadastre', 'Planning / Cadastre - Information used for appropriate actions for future use of the land.'), ('society', 'Society - Characteristics of society and cultures.'), ('structure', 'Structure - Man-made construction.'), ('transportation', 'Transportation - Means and aids for conveying persons and/or goods.'), ('utilitiesCommunication', 'Utilities / Communication - Energy, water and waste systems and communications infrastructure and services.')], help_text='Maps to pycsw:TopicCategory', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='xml',
            field=models.TextField(editable=False, help_text='Maps to pycsw:XML'),
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set([('catalog', 'identifier')]),
        ),
    ]
