# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-11 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_record_rndt_spatial_resolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='rndt_spatial_resolution',
        ),
        migrations.AlterField(
            model_name='record',
            name='denominator',
            field=models.IntegerField(blank=True, default='1000', max_length=255, null=True, verbose_name='Spatial resolution denominator'),
        ),
    ]
