# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-28 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20190411_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Maps to pycsw:CreationDate', null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Maps to pycsw:PublicationDate', null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='revision_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Maps to pycsw:RevisionDate', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Maps to pycsw:Modified', null=True),
        ),
    ]
