# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-28 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20200128_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='creation_date',
            field=models.DateField(auto_now_add=True, help_text='Maps to pycsw:CreationDate', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='modified_date',
            field=models.DateField(auto_now_add=True, help_text='Maps to pycsw:Modified', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='publication_date',
            field=models.DateField(auto_now_add=True, help_text='Maps to pycsw:PublicationDate', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='revision_date',
            field=models.DateField(auto_now_add=True, help_text='Maps to pycsw:RevisionDate', null=True),
        ),
    ]
