# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-29 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20200128_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='inspire_date',
            field=models.DateField(blank=True, help_text=' date of INSPIRE metadata offering (in ISO 8601 format), maps to dateStamp', null=True, verbose_name='inspire_date'),
        ),
    ]
