# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-29 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_auto_20200129_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='inspire_distributor_contact_email',
            field=models.CharField(blank=True, help_text='the email address of the distributor responsible for the INSPIRE/RNDT metadata', max_length=255, null=True, verbose_name='inspire_distributor_contact_email'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='inspire_distributor_contact_organization',
            field=models.CharField(blank=True, help_text='the organization name of the distributor responsible for the INSPIRE/RNDT metadata', max_length=255, null=True, verbose_name='inspire_distributor__contact_organization'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='inspire_distributor_contact_phone',
            field=models.CharField(blank=True, help_text='the telephone number of the distributor responsible for the INSPIRE/RNDT metadata', max_length=255, null=True, verbose_name='inspire_distributorcontact_phone'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='inspire_distributor_contact_url',
            field=models.CharField(blank=True, help_text='the URL of the distributor responsible for the INSPIRE/RNDT metadata', max_length=255, null=True, verbose_name='inspire_distributor_contact_url'),
        ),
    ]
