# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-29 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_auto_20200129_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='inspire_distributor_contact_email',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='inspire_distributor_contact_organization',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='inspire_distributor_contact_phone',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='inspire_distributor_contact_url',
        ),
        migrations.AddField(
            model_name='record',
            name='rndt_distributor_contact_email',
            field=models.CharField(blank=True, help_text='the email address of the distributor', max_length=255, null=True, verbose_name='RNDT distributor contact email'),
        ),
        migrations.AddField(
            model_name='record',
            name='rndt_distributor_contact_organization',
            field=models.CharField(blank=True, help_text='RNDT the organization name of the distributor', max_length=255, null=True, verbose_name='RNDT distributor contact organization'),
        ),
        migrations.AddField(
            model_name='record',
            name='rndt_distributor_contact_phone',
            field=models.CharField(blank=True, help_text='the telephone number of the distributor', max_length=255, null=True, verbose_name='RNDT distributor contact phone'),
        ),
        migrations.AddField(
            model_name='record',
            name='rndt_distributor_contact_url',
            field=models.CharField(blank=True, help_text='the URL of the distributor', max_length=255, null=True, verbose_name='RNDT distributor contact url'),
        ),
    ]
