# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-29 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_auto_20200129_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='inspire_contact_email',
            field=models.CharField(blank=True, help_text='the email address of entity responsible for the INSPIRE/RNDT metadata, inherited from catalog if left blank', max_length=255, null=True, verbose_name='inspire_contact_email'),
        ),
        migrations.AddField(
            model_name='record',
            name='inspire_contact_organization',
            field=models.CharField(blank=True, help_text='the organization name responsible for the INSPIRE/RNDT metadata, inherited from catalog if left blank', max_length=255, null=True, verbose_name='inspire_contact_organization'),
        ),
        migrations.AddField(
            model_name='record',
            name='inspire_contact_phone',
            field=models.CharField(blank=True, help_text='the telephone number of entity responsible for the INSPIRE/RNDT metadata, inherited from catalog if left blank', max_length=255, null=True, verbose_name='inspire_contact_phone'),
        ),
        migrations.AddField(
            model_name='record',
            name='inspire_contact_url',
            field=models.CharField(blank=True, help_text='the URL of entity responsible for the INSPIRE/RNDT metadata, inherited from catalog if left blank', max_length=255, null=True, verbose_name='inspire_contact_url'),
        ),
    ]
