# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-29 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20200129_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='project_keywords',
            field=models.TextField(blank=True, editable=False, help_text='These additional (not-GEMET) keywords are automatically updated form the getProjectSettings', null=True, verbose_name='Project keywords'),
        ),
    ]
