# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-13 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_auto_20200213_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='inspire_contact_email',
            field=models.CharField(blank=True, help_text='2.1.1.6 Responsabile dei metadati - the email address of entity responsible for the INSPIRE/RNDT metadata, inherited from catalog if left blank', max_length=255, null=True, verbose_name='2.1.1.6 INSPIRE contact email'),
        ),
        migrations.AlterField(
            model_name='record',
            name='inspire_contact_organization',
            field=models.CharField(blank=True, help_text='2.1.1.6 Responsabile dei metadati - the organization name responsible for the INSPIRE/RNDT metadata, inherited from catalog if left blank', max_length=255, null=True, verbose_name='2.1.1.6 ISPIRE contactorganization'),
        ),
        migrations.AlterField(
            model_name='record',
            name='inspire_contact_phone',
            field=models.CharField(blank=True, help_text='2.1.1.6 Responsabile dei metadati - the telephone number of entity responsible for the INSPIRE/RNDT metadata, inherited from catalog if left blank', max_length=255, null=True, verbose_name='2.1.1.6 INSPIRE contact phone'),
        ),
        migrations.AlterField(
            model_name='record',
            name='inspire_contact_url',
            field=models.CharField(blank=True, help_text='2.1.1.6 Responsabile dei metadati - the URL of entity responsible for the INSPIRE/RNDT metadata, inherited from catalog if left blank', max_length=255, null=True, verbose_name='2.1.1.6 INSPIRE contact url'),
        ),
    ]
