# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-14 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_auto_20200214_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='inspire_contact_email',
            field=models.CharField(blank=True, help_text='2.1.1.6 Responsabile dei metadati - the email address of entity responsible for the INSPIRE/RNDT metadata, inherited from catalog if left blank', max_length=255, null=True, verbose_name='2.1.2.10 INSPIRE contact email'),
        ),
        migrations.AlterField(
            model_name='record',
            name='inspire_contact_organization',
            field=models.CharField(blank=True, help_text='2.1.1.6 Responsabile dei metadati - the organization name responsible for the INSPIRE/RNDT metadata, inherited from catalog if left blank', max_length=255, null=True, verbose_name='2.1.2.10 ISPIRE contactorganization'),
        ),
        migrations.AlterField(
            model_name='record',
            name='inspire_contact_phone',
            field=models.CharField(blank=True, help_text='2.1.1.6 Responsabile dei metadati - the telephone number of entity responsible for the INSPIRE/RNDT metadata, inherited from catalog if left blank', max_length=255, null=True, verbose_name='2.1.2.10 INSPIRE contact phone'),
        ),
        migrations.AlterField(
            model_name='record',
            name='inspire_contact_url',
            field=models.CharField(blank=True, help_text='2.1.1.6 Responsabile dei metadati - the URL of entity responsible for the INSPIRE/RNDT metadata, inherited from catalog if left blank', max_length=255, null=True, verbose_name='2.1.2.10 INSPIRE contact url'),
        ),
        migrations.AlterField(
            model_name='record',
            name='rndt_distributor_contact_url',
            field=models.CharField(blank=True, help_text='2.1.7.2 Data distributor - the URL of the distributor, inherited from catalog if left blank', max_length=255, null=True, verbose_name='2.1.7.2 Data distributor: URL'),
        ),
        migrations.AlterField(
            model_name='record',
            name='security_constraints',
            field=models.CharField(blank=True, help_text='Maps to pycsw:SecurityConstraints', max_length=255, null=True, verbose_name='Security constraints'),
        ),
    ]
