# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-26 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_auto_20200225_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='inspire_conformity_service',
            field=models.CharField(blank=True, choices=[('conformant', 'conformant'), ('notConformant', 'notConformant'), ('notEvaluated', 'notEvaluated')], help_text='the level of INSPIRE conformance for spatial data sets and services (conformant, notConformant, notEvaluated)', max_length=20, null=True, verbose_name='Conformity INSPIRE'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='inspire_contact_email',
            field=models.CharField(blank=True, help_text='the email address of entity responsible for the INSPIRE/RNDT metadata', max_length=255, null=True, verbose_name='2.1.1.6 Contact point: email'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='inspire_contact_organization',
            field=models.CharField(blank=True, help_text='the organization name responsible for the INSPIRE/RNDT metadata', max_length=255, null=True, verbose_name='2.1.1.6 Contact point: organization'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='inspire_contact_phone',
            field=models.CharField(blank=True, help_text='the telephone number of entity responsible for the INSPIRE/RNDT metadata', max_length=255, null=True, verbose_name='2.1.1.6   Contact point: phone'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='inspire_contact_url',
            field=models.CharField(blank=True, help_text='the URL of entity responsible for the INSPIRE/RNDT metadata', max_length=255, null=True, verbose_name='2.1.1.6 Contact point: URL'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='inspire_default_language',
            field=models.CharField(blank=True, choices=[('bul', 'bul'), ('cze', 'cze'), ('dan', 'dan'), ('dut', 'dut'), ('eng', 'eng'), ('est', 'est'), ('fin', 'fin'), ('fre', 'fre'), ('ger', 'ger'), ('gre', 'gre'), ('hun', 'hun'), ('gle', 'gle'), ('ita', 'ita'), ('lav', 'lav'), ('lit', 'lit'), ('mlt', 'mlt'), ('pol', 'pol'), ('por', 'por'), ('rum', 'rum'), ('slo', 'slo'), ('slv', 'slv'), ('spa', 'spa'), ('swe', 'swe')], default='ita', help_text='3 letter code of the default language (see http://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_eng.xsd, simpleType euLanguageISO6392B)', max_length=255, null=True, verbose_name='2.1.1.2 Default language'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='inspire_geographical_extent',
            field=models.CharField(blank=True, help_text='Space separated values of lon/lat (west south east north)', max_length=255, null=True, verbose_name='Geographical extent'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='inspire_temp_extent',
            field=models.CharField(blank=True, help_text='temporal extent of the service (in ISO 8601 format). Either a single date (i.e. yyyy-mm-dd), or an extent (i.e. yyyy-mm-dd/yyyy-mm-dd)', max_length=255, null=True, verbose_name='Temporal extent validation'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(help_text='Name into CSW service URL', max_length=255, verbose_name='Catalog name'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='rndt_codice_ipa',
            field=models.CharField(help_text='RNDT: iPA administration code, a part fo file identifier', max_length=32, verbose_name='RNDT iPA administration code'),
        ),
        migrations.AlterField(
            model_name='record',
            name='access_constraints',
            field=models.TextField(blank=True, null=True, verbose_name='2.1.3.2 Access constraints'),
        ),
        migrations.AlterField(
            model_name='record',
            name='format',
            field=models.CharField(blank=True, help_text='2.1.7.1 Description about data format', max_length=50, null=True, verbose_name='2.1.7.1 Distribution format'),
        ),
        migrations.AlterField(
            model_name='record',
            name='identifier',
            field=models.CharField(db_index=True, help_text='2.1.2.5 File identifier - Maps to pycsw:Identifier', max_length=255, verbose_name='2.1.2.5 Identifier'),
        ),
        migrations.AlterField(
            model_name='record',
            name='inspire_contact_email',
            field=models.CharField(blank=True, help_text='2.1.2.10 Responsabile dei metadati - the email address of entity responsible for the INSPIRE/RNDT metadata, inherited from catalog if left blank', max_length=255, null=True, verbose_name='2.1.2.10 INSPIRE contact email'),
        ),
        migrations.AlterField(
            model_name='record',
            name='inspire_contact_organization',
            field=models.CharField(blank=True, help_text='2.1.2.10 Responsabile dei metadati - the organization name responsible for the INSPIRE/RNDT metadata, inherited from catalog if left blank', max_length=255, null=True, verbose_name='2.1.2.10 INSPIRE contactor ganization'),
        ),
        migrations.AlterField(
            model_name='record',
            name='inspire_contact_phone',
            field=models.CharField(blank=True, help_text='2.1.2.10 Responsabile dei metadati - the telephone number of entity responsible for the INSPIRE/RNDT metadata, inherited from catalog if left blank', max_length=255, null=True, verbose_name='2.1.2.10 INSPIRE contact phone'),
        ),
        migrations.AlterField(
            model_name='record',
            name='inspire_contact_url',
            field=models.CharField(blank=True, help_text='2.1.2.10 Responsabile dei metadati - the URL of entity responsible for the INSPIRE/RNDT metadata, inherited from catalog if left blank', max_length=255, null=True, verbose_name='2.1.2.10 INSPIRE contact url'),
        ),
        migrations.AlterField(
            model_name='record',
            name='keywords',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Addresses', 'Addresses'), ('Administrative units', 'Administrative units'), ('Agricultural and aquaculture facilities', 'Agricultural and aquaculture facilities'), ('Area management/restriction/regulation zones and reporting units', 'Area management/restriction/regulation zones and reporting units'), ('Atmospheric conditions', 'Atmospheric conditions'), ('Bio-geographical regions', 'Bio-geographical regions'), ('Buildings', 'Buildings'), ('Cadastral parcels', 'Cadastral parcels'), ('Coordinate reference systems', 'Coordinate reference systems'), ('Elevation', 'Elevation'), ('Energy resources', 'Energy resources'), ('Environmental monitoring facilities', 'Environmental monitoring facilities'), ('Geographical grid systems', 'Geographical grid systems'), ('Geographical names', 'Geographical names'), ('Geology', 'Geology'), ('Habitats and biotopes', 'Habitats and biotopes'), ('Human health and safety', 'Human health and safety'), ('Hydrography', 'Hydrography'), ('Land cover', 'Land cover'), ('Land use', 'Land use'), ('Meteorological geographical features', 'Meteorological geographical features'), ('Mineral resources', 'Mineral resources'), ('Natural risk zones', 'Natural risk zones'), ('Oceanographic geographical features', 'Oceanographic geographical features'), ('Orthoimagery', 'Orthoimagery'), ('Population distribution \u2014 demography', 'Population distribution \u2014 demography'), ('Production and industrial facilities', 'Production and industrial facilities'), ('Protected sites', 'Protected sites'), ('Sea regions', 'Sea regions'), ('Soil', 'Soil'), ('Species distribution', 'Species distribution'), ('Statistical units', 'Statistical units'), ('Transport networks', 'Transport networks'), ('Utility and governmental services', 'Utility and governmental services')], help_text='2.1.2.9 Record keywords - a comma-seperated keyword list of GEMET INSPIRE theme keywords about the service (see http://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_eng.xsd, complexType inspireTheme_eng)', max_length=1024, verbose_name='2.1.2.9 Keywords'),
        ),
        migrations.AlterField(
            model_name='record',
            name='language',
            field=models.CharField(blank=True, choices=[('bul', 'bul'), ('cze', 'cze'), ('dan', 'dan'), ('dut', 'dut'), ('eng', 'eng'), ('est', 'est'), ('fin', 'fin'), ('fre', 'fre'), ('ger', 'ger'), ('gre', 'gre'), ('hun', 'hun'), ('gle', 'gle'), ('ita', 'ita'), ('lav', 'lav'), ('lit', 'lit'), ('mlt', 'mlt'), ('pol', 'pol'), ('por', 'por'), ('rum', 'rum'), ('slo', 'slo'), ('slv', 'slv'), ('spa', 'spa'), ('swe', 'swe')], default='eng', help_text='2.1.2.14 Data Language', max_length=3, null=True, verbose_name='2.1.2.14 Language'),
        ),
        migrations.AlterField(
            model_name='record',
            name='modified_date',
            field=models.DateField(blank=True, help_text='2.1.2.2 Modified date', null=True, verbose_name='2.1.2.2 Modified date'),
        ),
        migrations.AlterField(
            model_name='record',
            name='other_constraints',
            field=models.TextField(blank=True, null=True, verbose_name='2.1.3.4 Other constraints'),
        ),
        migrations.AlterField(
            model_name='record',
            name='security_constraints',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='2.1.3.5 Security constraints'),
        ),
        migrations.AlterField(
            model_name='record',
            name='temporal_extent_begin',
            field=models.DateTimeField(blank=True, help_text='2.1.4.3 Start of data average time', max_length=255, null=True, verbose_name='2.1.4.3 Temporal extension: start'),
        ),
        migrations.AlterField(
            model_name='record',
            name='temporal_extent_end',
            field=models.DateTimeField(blank=True, help_text='2.1.4.3 End of data average time', max_length=255, null=True, verbose_name='2.1.4.3 Temporal extension: end'),
        ),
    ]
