# Generated by Django 2.2.16 on 2021-01-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_record_rndt_resource_maintenance_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='is_valid',
            field=models.BooleanField(default=True, help_text='This field is managed by signals, an invalid catalog will be regenerated by a management command called by CRON', verbose_name='Is valid'),
        ),
        migrations.AlterField(
            model_name='record',
            name='insert_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Maps to pycsw:InsertDate'),
        ),
        migrations.AlterField(
            model_name='record',
            name='rndt_resource_maintenance_frequency',
            field=models.CharField(choices=[('annually', 'data is updated every year'), ('asNeeded', "data is updated as deemed necessary, applies to resources with 'completed' status"), ('biannually', 'data is updated twice each year \t'), ('biennially', 'resource is updated every 2 years \t'), ('continual', 'data is repeatedly and frequently updated \tuse for data that is updated at a greater than daily frequency'), ('daily', 'data is updated each day \t'), ('fortnightly', 'data is updated every two weeks \t'), ('irregular', 'data is updated in intervals that are uneven in duration \t'), ('monthly', 'data is updated each month \t'), ('notPlanned', "there are no plans to update the data, applies to resources with 'completed' status"), ('periodic', 'resource is updated at regular intervals, '), ('quarterly', 'data is updated every three months'), ('semimonthly', 'resource updated twice a monthly'), ('unknown', 'frequency of maintenance for the data is not known'), ('weekly', 'data is updated on a weekly basis')], default='unknown', help_text='2.1.8.1 Frequenza con la quale sono registrati gli aggiornamenti dei dati.', max_length=255, verbose_name='2.1.8.1 Frequenza di aggiornamento'),
        ),
    ]
