# Generated by Django 2.2.16 on 2021-02-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_auto_20210204_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='g3w_project_id',
        ),
        migrations.AddField(
            model_name='record',
            name='g3w_layer_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='G3W-SUITE layer id/pk'),
        ),
    ]
