# Generated by Django 2.2.27 on 2022-03-15 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_auto_20220315_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='eu_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.UELicense'),
        ),
    ]
