# Generated by Django 2.2.27 on 2022-03-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0050_auto_20220315_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspireLimitationsOnPublicAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspire_id', models.CharField(max_length=400, verbose_name='OP code')),
                ('label', models.CharField(max_length=400, verbose_name='label')),
                ('definition', models.TextField(verbose_name='Definition')),
                ('url', models.URLField(verbose_name='Limitation URL')),
            ],
        ),
    ]
