# Generated by Django 2.2.27 on 2022-03-15 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0051_inspirelimitationsonpublicaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='access_constraints_inspire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.InspireLimitationsOnPublicAccess'),
        ),
    ]
