# Generated by Django 2.2.27 on 2022-03-16 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0052_record_access_constraints_inspire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspirelimitationsonpublicaccess',
            options={'ordering': ('label',)},
        ),
        migrations.AddField(
            model_name='record',
            name='usability_constraints',
            field=models.TextField(blank=True, null=True, verbose_name='2.4.3 Usability constraints'),
        ),
        migrations.AlterField(
            model_name='record',
            name='access_constraints',
            field=models.TextField(blank=True, null=True, verbose_name='2.4.2 Access constraints'),
        ),
        migrations.AlterField(
            model_name='record',
            name='access_constraints_inspire',
            field=models.ForeignKey(help_text='2.4.2 Select a access contraints from the list', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.InspireLimitationsOnPublicAccess', verbose_name='2.4.2 Access constraints'),
        ),
        migrations.AlterField(
            model_name='record',
            name='inspire_use_limitation',
            field=models.TextField(blank=True, help_text='2.4.1 Use limitation - Restrictions on data usage and access, inherited from catalog - No conditions apply - if left blank', null=True, verbose_name='2.4.1 Use limitation'),
        ),
    ]
