# Generated by Django 2.2.28 on 2022-10-19 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0056_auto_20220428_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='eu_license',
            field=models.ForeignKey(blank=True, help_text='Condizioni applicabili all\'accesso e all\'uso dei set di dati territoriali e ai relativi servizi e, ove applicabile, ai relativi corrispettivi, secondocon la legge dell\'articolo 5, comma 2, lettera b), e dell\'articolo 11,comma 2, lettera f), della Direttiva 2007/2/CE. | <a href="/catalog/eulicense"><i>Licenses list</i></a>', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.EULicense', verbose_name='Usability constraints - data license'),
        ),
    ]
