# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-18 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importdocfa',
            name='codice_comune',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='importdocfa',
            name='data_elaborazione',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importdocfa',
            name='n_docfa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importdocfa',
            name='n_planimetrie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importdocfa',
            name='n_record',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
