# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0011_config_codice_comune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='codice_comune',
            field=models.CharField(max_length=4),
        ),
    ]
