# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0012_auto_20171009_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodiciPartita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('F', b'FAB'), ('T', b'TER')], max_length=1)),
                ('partita', models.CharField(max_length=7)),
                ('descrizione', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'codici_partita',
                'verbose_name': 'Codice partita',
                'verbose_name_plural': 'Codici partita',
            },
        ),
        migrations.DeleteModel(
            name='PartiteSpeciali',
        ),
    ]
