# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-01 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0014_auto_20190130_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prm',
            name='codice_comune',
            field=models.CharField(max_length=10),
        ),
    ]
