# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-27 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0020_auto_20190227_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportCatasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('codice_comune', models.CharField(blank=True, max_length=4, null=True)),
                ('n_file', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to=b'catasto_files')),
                ('task_id', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Import Geometric Cadastre',
                'verbose_name_plural': 'Import Geometric Cadastre',
            },
        ),
    ]
