# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-27 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0021_importcatasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='importcatasto',
            name='fogli',
            field=models.TextField(blank=True, null=True),
        ),
    ]
