# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-28 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0022_importcatasto_fogli'),
    ]

    operations = [
        migrations.AddField(
            model_name='catasto',
            name='task_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importcatasto',
            name='sup_data',
            field=models.TextField(null=True),
        ),
    ]
