# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-08 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0026_configimportcxf_db_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformCatasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foglio', models.CharField(max_length=255)),
                ('transform', models.TextField()),
            ],
        ),
    ]
