# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-08 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0027_transformcatasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='catasto',
            name='data_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catasto',
            name='data_ini',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
