# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-25 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0031_auto_20191003_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='planimetrieiniziali',
            name='sezione',
            field=models.ForeignKey(blank=True, db_column='sezione', null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastre.SezioniCensuarie'),
        ),
    ]
