# Generated by Django 2.2.20 on 2021-05-13 13:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0034_auto_20210427_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='configimportcxf',
            name='provider',
            field=models.CharField(choices=[('postgresql', 'PostgreSql'), ('oracle', 'Oracle')], default='postgresql',  max_length=40, verbose_name='DB Provider'),
        ),
        migrations.AlterField(
            model_name='catasto',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=32633),
        ),
    ]
