# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0004_planimetrieiniziali'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificativiimmobiliari',
            name='id_immobile',
            field=models.IntegerField(unique=True),
        ),
    ]
