# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 09:48
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0007_auto_20171006_0701'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='particella',
            managers=[
                ('cadastre_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='personafisica',
            unique_together=set([('id_soggetto', 'codice_comune', 'luogo_nascita')]),
        ),
        migrations.RunSQL(
            "CREATE UNIQUE INDEX persona_fisica_id_soggetto_codice_comun_0272286e_indie ON public.persona_fisica "
            "USING btree ("
            "id_soggetto, "
            "(COALESCE(codice_comune, '0000'::character varying)) COLLATE pg_catalog.\"default\", "
            "(COALESCE(luogo_nascita, 'AAAA'::character varying)) COLLATE pg_catalog.\"default\")"
        ),
        migrations.AlterUniqueTogether(
            name='personagiuridica',
            unique_together=set([('id_soggetto', 'codice_comune', 'sede')]),
        ),
        migrations.RunSQL(
            "CREATE UNIQUE INDEX persona_giuridica_id_soggetto_codice_comune_sede_e042037c_inde "
            "ON public.persona_giuridica "
            "USING btree ("
            "id_soggetto, "
            "(COALESCE(codice_comune, '0000'::character varying)) COLLATE pg_catalog.\"default\", "
            "(COALESCE(sede, 'AAAA'::character varying)) COLLATE pg_catalog.\"default\")"
        )
    ]
