# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0008_auto_20171006_0948'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='personafisica',
            managers=[
                ('cadastre_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='personagiuridica',
            managers=[
                ('cadastre_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='planimetrieiniziali',
            name='nome_file',
            field=models.TextField(),
        ),
    ]
