# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0009_auto_20171009_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='istatcodiciui',
            options={'managed': True, 'verbose_name': 'ISTAT Codici UI', 'verbose_name_plural': 'ISTAT Codici UI'},
        ),
    ]
