# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-30 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0013_auto_20171030_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitaimmobiliare',
            name='consistenza',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
