# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-01 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0015_auto_20190201_1538'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP INDEX identificativi_immobilia_id_immobile_progressivo__dd9f0540_inde"
        ),
        migrations.RunSQL(
            "DROP INDEX particella_id_particella_progressiv_093d31c1_inde"
        ),
        migrations.AlterField(
            model_name='caratteristicheparticella',
            name='sezione',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='deduzioniparticella',
            name='sezione',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='identificativiimmobiliari',
            name='sezione',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='indirizzi',
            name='sezione',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='particella',
            name='sezione',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='porzioniparticella',
            name='sezione',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='relazionefabbricatidocfa',
            name='sezione',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='riserveparticella',
            name='sezione',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='riserveui',
            name='sezione',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='titolarita',
            name='sezione',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='unitaimmobiliare',
            name='sezione',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='utilitacomuniui',
            name='sezione',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.RunSQL(
            "CREATE UNIQUE INDEX identificativi_immobilia_id_immobile_progressivo__dd9f0540_inde "
            "ON public.identificativi_immobiliari "
            "USING btree ("
            "id_immobile, "
            "(COALESCE(progressivo, '-1'::integer)), "
            "(COALESCE(codice_comune, '0000'::character varying)) COLLATE pg_catalog.\"default\", "
            "(COALESCE(sezione_urbana, '-1-1-1'::character varying)) COLLATE pg_catalog.\"default\", "
            "(COALESCE(sezione, '-1'::character varying)), "
            "(COALESCE(foglio, 'AAAA'::character varying)) COLLATE pg_catalog.\"default\", "
            "(COALESCE(numero, 'AAAAA'::character varying)) COLLATE pg_catalog.\"default\", "
            "(COALESCE(denominatore, '-1'::integer)), "
            "(COALESCE(subalterno, 'AAAA'::character varying)) COLLATE pg_catalog.\"default\")"
        ),
        migrations.RunSQL(
            "CREATE UNIQUE INDEX particella_id_particella_progressiv_093d31c1_inde "
            "ON public.particella USING btree ("
            "id_particella, "
            "(COALESCE(progressivo, '-1'::integer)), "
            "(COALESCE(codice_comune, '0000'::character varying)) COLLATE pg_catalog.\"default\", "
            "(COALESCE(sezione, '-1'::character varying)), "
            "(COALESCE(foglio, 'AAAA'::character varying)) COLLATE pg_catalog.\"default\", "
            "(COALESCE(numero, 'AAAAA'::character varying)) COLLATE pg_catalog.\"default\", "
            "(COALESCE(denominatore, '-1'::integer)), "
            "(COALESCE(subalterno, 'AAAA'::character varying)) COLLATE pg_catalog.\"default\")"
        )
    ]
