# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0018_cadastredataaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='attrs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
