# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-02 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0025_configimportcxf_configusercadastre'),
    ]

    operations = [
        migrations.AddField(
            model_name='configimportcxf',
            name='db_table',
            field=models.CharField(default=None, max_length=255, verbose_name='DB table'),
            preserve_default=False,
        ),
    ]
