# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-28 13:11
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20190304_1709'),
        ('cadastre', '0029_auto_20190410_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='configimportcxf',
            name='srid',
            field=models.ForeignKey(db_column='srid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.G3WSpatialRefSys'),
        ),
        migrations.AlterField(
            model_name='catasto',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=3003),
        ),
    ]
