# Generated by Django 2.2.23 on 2021-07-29 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0035_auto_20210513_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastre.Config')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='qdjango.Layer')),
            ],
        ),
    ]
