# Generated by Django 2.2.27 on 2022-03-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0038_auto_20220225_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personafisica',
            name='luogo_nascita',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Luogo di nascita'),
        ),
        migrations.AlterField(
            model_name='personagiuridica',
            name='sede',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
