# Generated by Django 2.2.27 on 2022-03-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0039_auto_20220310_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagiuridica',
            name='id_soggetto',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
