# Generated by Django 2.2.28 on 2022-10-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0041_auto_20220311_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caratteristicheparticella',
            name='annotazione',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
