# Generated by Django 2.2.28 on 2022-11-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0042_auto_20221011_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planimetrie',
            name='numero',
            field=models.BigIntegerField(),
        ),
    ]
