# Generated by Django 2.2.28 on 2022-11-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0043_auto_20221130_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planimetrie',
            name='numero',
            field=models.TextField(),
        ),
    ]
