# Generated by Django 2.2.28 on 2022-12-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0044_auto_20221130_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docfa',
            name='data_registrazione',
            field=models.DateField(blank=True, null=True),
        ),
    ]
