# Generated by Django 2.2.28 on 2023-02-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0045_auto_20221202_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitaimmobiliare',
            name='annotazione',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
