# Generated by Django 2.2.28 on 2023-04-18 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0046_auto_20230217_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configlayer',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdjango.Layer'),
        ),
    ]
