# Generated by Django 3.2.25 on 2024-05-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0047_auto_20230418_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='configimportcxf',
            name='transfom',
            field=models.BooleanField(default=True, verbose_name='Apply transformation (for CRS)'),
        ),
    ]
