# Generated by Django 3.2.25 on 2024-05-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0048_configimportcxf_transfom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configimportcxf',
            old_name='transfom',
            new_name='transform',
        ),
    ]
