# Generated by Django 2.2.18 on 2021-04-08 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qdjango', '0076_geoconstraint_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleRepoProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simplereporting_projects', to='qdjango.Project')),
            ],
            options={
                'verbose_name': 'Simple Reporting Project',
            },
        ),
        migrations.CreateModel(
            name='SimpleRepoLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('layer', models.ForeignKey(help_text='Select vector project layer to use for reporting', on_delete=django.db.models.deletion.CASCADE, related_name='simplerepo_layer', to='qdjango.Layer')),
                ('simplerepo_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simplerepo_layer', to='simplereporting.SimpleRepoProject')),
            ],
            options={
                'verbose_name': 'Simple reporting vector Layer',
            },
        ),
    ]
