# Generated by Django 2.2.18 on 2021-04-09 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplereporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplerepolayer',
            name='simplerepo_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simplerepo_layer', to='simplereporting.SimpleRepoProject', unique=True),
        ),
        migrations.AlterField(
            model_name='simplerepoproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simplereporting_projects', to='qdjango.Project', unique=True),
        ),
    ]
