# Generated by Django 2.2.18 on 2021-04-09 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplereporting', '0002_auto_20210409_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplerepolayer',
            name='simplerepo_project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simplerepo_layer', to='simplereporting.SimpleRepoProject'),
        ),
        migrations.AlterField(
            model_name='simplerepoproject',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simplereporting_projects', to='qdjango.Project'),
        ),
    ]
