# Generated by Django 2.2.20 on 2021-04-09 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplereporting', '0004_auto_20210409_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplerepolayer',
            name='layer',
            field=models.ForeignKey(help_text='Select vector project layer to use for reporting', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simplerepo_layer', to='qdjango.Layer'),
        ),
    ]
