# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-21 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdu', '0002_cduresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configs',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qdjango.Project'),
        ),
    ]
