# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdu', '0003_auto_20180621_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='configs',
            name='output_format',
            field=models.CharField(choices=[('odt', 'ODT')], max_length=3, null=True, verbose_name='Results output format'),
        ),
    ]
