# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdu', '0004_configs_output_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='configs',
            name='map_image',
            field=models.CharField(choices=[('map', 'Whole map'), ('layer', 'Only Cadastre Layer')], default='map', max_length=10, null=True, verbose_name='Map image'),
        ),
        migrations.AlterField(
            model_name='configs',
            name='output_format',
            field=models.CharField(choices=[('odt', 'ODT'), ('pdf', 'PDF'), ('doc', 'DOC'), ('dox', 'DOX')], max_length=3, null=True, verbose_name='Results output format'),
        ),
    ]
