# Generated by Django 2.2.9 on 2020-01-07 11:14

from django_extensions.db import fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdu', '0006_auto_20191003_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configs',
            options={'permissions': (('make_cdu', 'Can make CDU analisys'),)},
        ),
        migrations.AlterField(
            model_name='cduresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='configs',
            name='slug',
            field=fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True, verbose_name='Slug'),
        ),
    ]
